#!/bin/bash

set -e

export UFS_DOMAIN_SELECT_HOME=`echo $(realpath $(dirname $0))`

echo "Initializing conda..."
eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

echo "Activating ufs_domain_select..."
conda activate ufs_domain_select

echo "Launching GUI..."

export QT_QPA_PLATFORM=xcb

${UFS_DOMAIN_SELECT_HOME}/UFS_domain_select.py
