#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=`echo $(realpath $(dirname $0))`

echo "Initializing conda..."
eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

echo "Activating regional_workflow-$VER..."
conda activate regional_workflow-$VER

echo "Launching GUI..."

export QT_QPA_PLATFORM=xcb

${UFS_DOMAIN_SELECT_HOME}/UFS_domain_select.py
