#!/bin/bash

\rm -rf ${UFS_DOMAIN_SELECT_HOME}/build/expt-2.2.0/
./do-forecast 2.2.0
./do-post 2.2.0
cd ${UFS_DOMAIN_SELECT_HOME}/build/expt-2.2.0/test_community/2019061518/postprd
~/UFS_domain_select/forecast/do-plot &
#ristretto ~/expt-2.2.0/test_community/2025040312/postprd/*.png
