#!/bin/bash

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
\rm -rf ${UFS_DOMAIN_SELECT_HOME}/build/expt-2.2.0/
${UFS_DOMAIN_SELECT_HOME}/forecast/do-forecast 2.2.0
${UFS_DOMAIN_SELECT_HOME}/forecast/do-post 2.2.0
cd ${UFS_DOMAIN_SELECT_HOME}/build/expt-2.2.0/test_community/2019061518/postprd
${UFS_DOMAIN_SELECT_HOME}/forecast/do-plot
