#!/bin/bash

set -e

if [ $# != 2 ]; then
        echo "usage: $0 <hpc|spack> <2.2.0|3.0.0>"
        exit 1
fi

if [ ! $1 == "hpc" ] && [ ! $1 == "spack" ]; then
	echo \"$1\" is an invalid stack
        echo "usage: $0 <hpc|spack> <2.2.0|3.0.0>"
	exit 1 
fi

if [ "$2" == "2.2.0" ]; then
	STACK=$1
	VER=$2
elif [ "$2" == "3.0.0" ]; then
	STACK=$1
	VER=$2
else
        echo "$2 not supported"
        exit 1
fi

#
# Be careful here. The setting of EXPT_SUBDIR leads to strange
# errors in run_make_orog.sh, particularly if the path length
# is too long.
#
export UFS_DOMAIN_SELECT_HOME=`echo $(realpath $(dirname $0))/.. | sed 's/\/forecast\/\.\.//'`

EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/exp-$STACK-$VER
EXPT_SUBDIR=test

#EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/expt
#EXPT_SUBDIR=test_${STACK}

echo "### Experiment path is $EXPT_BASEDIR/$EXPT_SUBDIR"
length=`echo $EXPT_BASEDIR/$EXPT_SUBDIR | wc -c`
echo "length is $length"
sleep 1

if [ $length -gt 61 ]; then
	echo
	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
	echo "Path length is $length"
	echo "Path length cannot exceed 61 bytes"
	#exit 1
fi

EXTRN_MDL_SOURCE_BASEDIR_ICS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518
EXTRN_MDL_SOURCE_BASEDIR_LBCS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518

export EXPTDIR=$EXPT_BASEDIR/$EXPT_SUBDIR

#
# Apply patches to UFS
#

cd ${UFS_DOMAIN_SELECT_HOME}/forecast

ncores_per_node=`lscpu -p | egrep -v '^#' | wc -l`

layout_x=`echo "sqrt($ncores_per_node)" | bc`
layout_y=$layout_x

cat config.yaml.tmpl | sed "s|<EXPT_SUBDIR>|${EXPT_SUBDIR}|g" | sed "s|<EXPT_BASEDIR>|${EXPT_BASEDIR}|g" | sed "s|<EXTRN_MDL_SOURCE_BASEDIR_ICS>|${EXTRN_MDL_SOURCE_BASEDIR_ICS}|g" | sed "s|<EXTRN_MDL_SOURCE_BASEDIR_LBCS>|${EXTRN_MDL_SOURCE_BASEDIR_LBCS}|g" | sed "s|<LAYOUT_X>|${layout_x}|g" | sed "s|<LAYOUT_Y>|${layout_y}|g" | sed "s|<NCORES_PER_NODE>|${ncores_per_node}|g" | sed "s|<UFS_DOMAIN_SELECT_HOME>|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/config.yaml

cat linux-$VER.yaml.tmpl | sed "s|<UFS_DOMAIN_SELECT_HOME>|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/machine/linux.yaml

#
# Activate spack environment, if needed
#

if [ $STACK == "spack" ]; then
	echo "### Initializing spack..."
	source $UFS_DOMAIN_SELECT_HOME/build/$STACK-stack-for-$VER/share/spack/setup-env.sh
	if [ $STACK == "spack" ]; then
		ENV="ufs"
	fi
	echo "### Activating $ENV spack environment..."
	spack env activate $ENV -p

	#
	# Certain shared libraries cannot be found, like the ones below.
	# Enabling LD_LIBRARY_PATH in the build-spack-stack script fixes
	# this for now.
	#
        #export LD_LIBRARY_PATH="`spack location -i jasper`/lib:$LD_LIBRARY_PATH"
        #export LD_LIBRARY_PATH="`spack location -i netcdf-c`/lib:$LD_LIBRARY_PATH"
        #export LD_LIBRARY_PATH="`spack location -i netcdf-fortran`/lib:$LD_LIBRARY_PATH"
        #export LD_LIBRARY_PATH="`spack location -i parallelio`/lib:$LD_LIBRARY_PATH"
	#export LD_LIBRARY_PATH="`spack location -i libjpeg-turbo`/lib:$LD_LIBRARY_PATH"
elif [ $STACK == "hpc" ]; then
	# We only need this to add the mpi executables to PATH
	source $UFS_DOMAIN_SELECT_HOME/scripts/load-hpc-stack $VER
fi

#
# Activate conda environment
#

echo "### Initializing conda..."
eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

echo "### Activating regional_workflow-$VER..."
conda activate regional_workflow-$VER

if [ "$VER" == "2.2.0" ]; then
	export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/python_utils/workflow-tools/"
	export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/python_utils/workflow-tools/src"
fi

echo "### Generating forecast..."
cd ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush
./generate_FV3LAM_wflow.py

cd $EXPTDIR

if [ "$VER" == "2.2.0" ]; then
	cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/wrappers/* .
elif [ "$VER" == "3.0.0" ]; then
	export USHdir="${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush"
	export JOBSdir="${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/jobs"
	export PW_CSP="foobar"
	cd $USHdir/wrappers
fi

./run_make_grid.sh
./run_get_ics.sh
./run_get_lbcs.sh
./run_make_orog.sh
./run_make_sfc_climo.sh
./run_make_ics.sh
./run_make_lbcs.sh
./run_fcst.sh
./run_post.sh

${UFS_DOMAIN_SELECT_HOME}/forecast/do-plot $STACK $VER
