#!/bin/bash

if [ $# != 2 ]; then
        echo "usage: $0 <hpc|spack|spack-lmod> <2.2.0|3.0.0>"
        exit 1
fi

if [ ! $1 == "hpc" ] && [ ! $1 == "spack" ] && [ ! $1 == "spack-lmod" ]; then
	echo \"$1\" is an invalid stack
        echo "usage: $0 <hpc|spack|spack-lmod> <2.2.0|3.0.0>"
	exit 1 
fi

if [ "$2" == "2.2.0" ]; then
	STACK=$1
	VER=$2
elif [ "$2" == "3.0.0" ]; then
        echo "$1 not yet implemented"
        exit 1
else
        echo "$2 not supported"
        exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
export EXPTDIR=${EXPT_BASEDIR}/ufs_domain_select_OR_coast

#
# Apply patches to UFS
#

cd ${UFS_DOMAIN_SELECT_HOME}/forecast
cp config.yaml ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush
cat linux-$VER.yaml | sed "s|UFS_DOMAIN_SELECT_HOME|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/machine/linux.yaml

#
# Activate spack environment, if needed
#

if [ $STACK == "spack" ] || [ $STACK == "spack-lmod" ]; then
	#source $UFS_DOMAIN_SELECT_HOME/build/$STACK-stack-for-$VER/share/spack/setup-env.sh || exit 1
	source $UFS_DOMAIN_SELECT_HOME/build/spack-stack-for-$VER/share/spack/setup-env.sh || exit 1
	if [ $STACK == "spack" ]; then
		ENV="ufs"
	else
		ENV="ufs-lmod"
	fi
	echo "### $0: activating $ENV spack environment"
	spack env activate $ENV -p || exit 1
        export LD_LIBRARY_PATH="`spack location -i jasper`/lib:$LD_LIBRARY_PATH"
        export LD_LIBRARY_PATH="`spack location -i netcdf-c`/lib:$LD_LIBRARY_PATH"
        export LD_LIBRARY_PATH="`spack location -i netcdf-fortran`/lib:$LD_LIBRARY_PATH"
        export LD_LIBRARY_PATH="`spack location -i parallelio`/lib:$LD_LIBRARY_PATH"
fi

#
# Activate conda environment
#

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
conda activate regional_workflow-$VER
export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-$STACK-stack/ush/python_utils/workflow-tools/"
export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-$STACK-stack/ush/python_utils/workflow-tools/src"

cd ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/
./generate_FV3LAM_wflow.py || exit 1
cd ${EXPTDIR}
cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/wrappers/* .

./run_make_grid.sh || exit 1
./run_get_ics.sh || exit 1
./run_get_lbcs.sh || exit 1
./run_make_orog.sh || exit 1
./run_make_sfc_climo.sh || exit 1
./run_make_ics.sh || exit 1
./run_make_lbcs.sh || exit 1
./run_fcst.sh || exit 1
./run_post.sh || exit 1
