#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

if [ "$1" == "2.2.0" ]; then
	VER=$1
elif [ "$1" == "3.0.0" ]; then
        echo "$1 not yet implemented"
        exit 1
else
        echo "$1 not supported"
        exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

#
# Patch files
#
cd ${UFS_DOMAIN_SELECT_HOME}/forecast

cp config-spack.yaml ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-spack-stack/ush/config.yaml

cat linux-$VER.yaml | sed "s|UFS_DOMAIN_SELECT_HOME|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-spack-stack/ush/machine/linux.yaml
#cp wflow_linux-$VER.lua ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER/modulefiles/wflow_linux.lua

export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
export EXPTDIR=${EXPT_BASEDIR}/ufs_domain_select_OR_coast

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

if [ $VER == "2.1.0" ]; then
	conda activate regional_workflow-2.1.0
fi
if [ $VER == "2.2.0" ]; then

        echo "### $0: activating ufs spack environment"
	source $UFS_DOMAIN_SELECT_HOME/build/spack-stack-for-$VER/share/spack/setup-env.sh || exit 1
	spack env activate ufs -p || exit 1
	export LD_LIBRARY_PATH="`spack location -i jasper`/lib:$LD_LIBRARY_PATH"
	export LD_LIBRARY_PATH="`spack location -i netcdf-c`/lib:$LD_LIBRARY_PATH"
	export LD_LIBRARY_PATH="`spack location -i netcdf-fortran`/lib:$LD_LIBRARY_PATH"
	export LD_LIBRARY_PATH="`spack location -i parallelio`/lib:$LD_LIBRARY_PATH"

        echo "### $0: activating conda environment"
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.2.0

        export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-spack-stack/ush/python_utils/workflow-tools/"
        export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-spack-stack/ush/python_utils/workflow-tools/src"
fi

cd ${UFS_DOMAIN_SELECT_HOME}/build//ufs-srweather-app-$VER-with-spack-stack/ush/
./generate_FV3LAM_wflow.py || exit 1
cd ${EXPTDIR}
cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-spack-stack/ush/wrappers/* .

./run_make_grid.sh || exit 1
./run_get_ics.sh || exit 1
./run_get_lbcs.sh || exit 1
./run_make_orog.sh || exit 1
./run_make_sfc_climo.sh || exit 1
./run_make_ics.sh || exit 1
./run_make_lbcs.sh || exit 1
./run_fcst.sh || exit 1
./run_post.sh || exit 1
