#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

#
# Patch files
#
cd ${UFS_DOMAIN_SELECT_HOME}/forecast
cp config-hpc.yaml ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack/ush/config.yaml
cat linux-$VER.yaml | sed "s|UFS_DOMAIN_SELECT_HOME|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack/ush/machine/linux.yaml
#cp wflow_linux-$VER.lua ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack/modulefiles/wflow_linux.lua

export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
export EXPTDIR=${EXPT_BASEDIR}/test_hpc

if [ $VER == "2.1.0" ]; then
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.1.0
fi
if [ $VER == "2.2.0" ]; then
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.2.0
        export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-hpc-stack/ush/python_utils/workflow-tools/"
        export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2.2.0-with-hpc-stack/ush/python_utils/workflow-tools/src"
fi

cd ${UFS_DOMAIN_SELECT_HOME}/build//ufs-srweather-app-$VER-with-hpc-stack/ush/
./generate_FV3LAM_wflow.py || exit 1

cd ${EXPTDIR}
cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack/ush/wrappers/* .

./run_make_grid.sh || exit 1
./run_get_ics.sh || exit 1
./run_get_lbcs.sh || exit 1
./run_make_orog.sh || exit 1
./run_make_sfc_climo.sh || exit 1
./run_make_ics.sh || exit 1
./run_make_lbcs.sh || exit 1
./run_fcst.sh || exit 1
./run_post.sh || exit 1
