#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
export EXPTDIR=${EXPT_BASEDIR}/test_hpc

if [ $VER == "2.1.0" ]; then
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.1.0 || exit 1
fi
if [ $VER == "2.2.0" ]; then
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.2.0 || exit 1
fi

cd $EXPTDIR

./run_post.sh || exit 1
