#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

conda activate regional_workflow-v$VER

cd ${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs/test_spack/*/postprd/

rm -f *.png

for i in `ls PRSLEV*`; do
	cmd="$UFS_DOMAIN_SELECT_HOME/UFS_domain_select.py -f $i -x";
	echo $cmd
	$cmd
done

ristretto *.png &
