#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

if [ "$1" == "2.2.0" ]; then
        VER=$1
else
        echo "$1 not supported"
        exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

conda activate regional_workflow-$VER || exit 1

cd ${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs/ufs_domain_select_test/*/postprd/

rm -f *.png

for i in `ls PRSLEV*`; do
	cmd="$UFS_DOMAIN_SELECT_HOME/UFS_domain_select.py -f $i -x";
	echo $cmd
	$cmd || exit 1
done

ristretto *.png &
