#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
        exit 1
fi

if [ "$1" == "2.2.0" ]; then
        VER=$1
else
        echo "$1 not supported"
        exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
export EXPTDIR=${EXPT_BASEDIR}/ufs_domain_select_test

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
conda activate regional_workflow-$VER || exit 1

cd $EXPTDIR || exit 1

./run_post.sh || exit 1
