#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt-$VER
export EXPTDIR=${EXPT_BASEDIR}/test_community

if [ $VER == "2.1.0" ]; then
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate regional_workflow-2.1.0
fi
if [ $VER == "2.2.0" ]; then
	source /usr/local/lmod/lmod/init/profile
	module use ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-v$VER/modulefiles
	module load wflow_linux
	eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
	conda activate workflow_tools
fi

cd ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-v$VER/ush/
cd $EXPTDIR

source /usr/local/lmod/lmod/init/profile
module use ${UFS_DOMAIN_SELECT_HOME}/build/opt-$VER/modulefiles/stack
module load hpc hpc-gnu hpc-openmpi
module load netcdf

./run_post.sh
