#!/bin/bash

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

MESNIER_PDY="20190615"
MESNIER_PDY="20250626"
MESNIER_PDY="20250627"
MESNIER_CYC="00"

flag=0; while [ 1 ]; do if ls ${UFS_DOMAIN_SELECT_HOME}/build/expt-2.2.0/test_community/$MESNIER_PDY$MESNIER_CYC/*.nc >/dev/null 2>&1; then echo -e "*** READY ***"; if [ $flag == 0 ]; then echo -e "\a"; sleep 1; echo -e "\a"; sleep 1; echo -e "\a"; echo "sleeping 30..."; sleep 30; killall ufs_model; flag=1; fi; else echo "NOT READY"; flag=0; fi; sleep 1; clear; done
