#!/bin/bash

if ! [[ "$0" == "bash" ]] || [[ "$0" == "-bash" ]] || [[ "$0" == "/bin/bash" ]]; then
    echo "Script must be sourced, not executed directly."
    exit 1
fi

cd ~
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc
source ~/spack/share/spack/setup-env.sh

spack env create foobar --without-view
spack env activate foobar -p
echo "spack env activate foobar -p" >> ~/.bashrc

echo "\"spack edit fms\" and add args.append(\"-D64BIT:BOOL=ON\") to fms cmake_args"
read -p "Enter to continue"

PACKAGES="gcc@9.3.0 openmpi@4.0.1 cmake@3.20.6 netcdf-c@4.9.2 netcdf-fortran esmf@8.4.2 fms@2023.01 bacio@2.4.1 crtm@2.4.0 g2@3.4.5 g2tmpl@1.10.2 nemsio@2.5.4 sfcio@1.4.1 sigio@2.3.2 sp@2.3.3 ip@3.3.3"

for i in $PACKAGES; do
	spack install --add --deprecated --force $i
	spack load $i
done

export ESMFMKFILE=`find ~/spack -name esmf.mk`
echo export ESMFMKFILE=`find ~/spack -name esmf.mk` >> ~/.bashrc
