#!/bin/bash

if [ $# != 1 ]; then
	echo "usage: build-stack <2.1.0|2.2.0>"
	exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

mkdir -p $UFS_DOMAIN_SELECT_HOME/build

git clone https://github.com/NOAA-EMC/hpc-stack.git -b develop ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER

echo "### COPYING PATCH FILES FROM ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER TO ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER ###"
(cd ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER; git reset fa37037)
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/build_* ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER/libs
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/config_custom.sh ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER/config
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/stack_custom.yaml ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER/stack

cd ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER

source /usr/local/lmod/lmod/init/profile

read -p "<Enter> to configure"
yes YES | ./setup_modules.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -c ./config/config_custom.sh

read -p "<Enter> to build"
./build_stack.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -c ./config/config_custom.sh -y stack/stack_custom.yaml -m
