#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: build-model <2.1.0|2.2.0>"
        exit 1
fi

VER=v$1
SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER

sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

cd
git clone -b release/public-$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC
cd $SRC
./manage_externals/checkout_externals

cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/lmod-setup.sh etc
#cp ~/trunk/attic/NOAA-2024/srw_common.lua modulefiles

source /usr/local/lmod/lmod/init/bash
module use ${UFS_DOMAIN_SELECT_HOME}/build/opt-$1/modulefiles/stack
module load hpc hpc-gnu hpc-openmpi

sudo apt install curl -y

#mv ~/anaconda3 ~/anaconda3-disabled
./devbuild.sh --platform=linux --compiler=gnu
#mv ~/anaconda3-disabled ~/anaconda3
