#!/bin/bash

set -e

if [ $# != 1 ]; then
	echo "usage: build-stack <2.2.0|3.0.0>"
	exit 1
fi

if ! cat /etc/issue | awk '{print $2}' | grep -E "^18|^22|^24"; then
	echo "`cat /etc/issue` has not been tested"
	exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

mkdir -p $UFS_DOMAIN_SELECT_HOME/build

#
# Clone and patch git repo
#
git clone https://github.com/NOAA-EMC/hpc-stack.git ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER
cd ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER
git checkout fa370370f912fe491a53aad26e0266ce7552eee7

echo "### COPYING PATCH FILES FROM ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER TO ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-for-$VER ###"

if [ $VER == "2.2.0" ]; then
	cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/build_* ./libs
fi

cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/build_* ./libs

cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/config_custom.sh ./config
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/hpc-stack-for-$VER/stack_custom.yaml ./stack

#
# Initialize Lmod
#
source /usr/local/lmod/lmod/init/profile

yes Yes | ./setup_modules.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -c ./config/config_custom.sh

# For bootstrapping with cmake and openmpi
export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH
#export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11.4/openmpi/4.1.2/bin:"$PATH
#export LD_LIBRARY_PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11.4/openmpi/4.1.2/lib:"$LD_LIBRARY_PATH

./build_stack.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -c ./config/config_custom.sh -y stack/stack_custom.yaml -m
