#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: build-model <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack

cd
if [ ! -d $SRC ]; then
	git clone -b release/public-v$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC
fi
cd $SRC
./manage_externals/checkout_externals || exit 1

cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/ufs-srweather-app-$VER-with-hpc-stack/lmod-setup.sh etc
if [ $VER == "3.0.0" ]; then
	cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/ufs-srweather-app-$VER-with-hpc-stack/CMakeLists.txt sorc/UPP/sorc/ncep_post.fd
	cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/ufs-srweather-app-$VER-with-hpc-stack/devbuild.sh .
fi

export LMOD_PAGER=none

source /usr/local/lmod/lmod/init/bash
module use ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$1/modulefiles/stack
module load hpc hpc-gnu hpc-openmpi
module list

export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH

cd $SRC
BUILD_UFS_UTILS=off ./devbuild.sh --platform=linux --compiler=gnu
