#!/bin/bash

if ! [[ "$0" == "bash" ]] || [[ "$0" == "-bash" ]] || [[ "$0" == "/bin/bash" ]]; then
    echo "Script must be sourced, not executed directly."
    exit 1
fi

cd ~
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc
source ~/spack/share/spack/setup-env.sh

spack env create ufs
spack env activate ufs -p
echo "spack env activate ufs -p" >> ~/.bashrc

echo "\"spack edit fms\" and add args.append(\"-D64BIT:BOOL=ON\") to fms cmake_args"
read -p "Enter to continue"

spack compiler find

spack add openmpi@5.0.9 jasper@2.0.32 libpng@1.6.37 netcdf-c@4.9.2 netcdf-fortran@4.6.1 parallelio@2.5.10
spack add esmf@8.6.0 fms@2024.01
spack add bacio@2.4.1 crtm@2.4.0.1 g2@3.5.1 g2tmpl@1.13.0 ip@4.3.0 sp@2.5.0 w3emc@2.10.0 gftl-shared@1.6.1
spack add mapl@2.40.3 ^esmf@8.6.0
spack add nemsio@2.5.4 sfcio@1.4.1 sigio@2.3.2 w3nco@2.4.1 wrf-io@1.2.0
spack add wgrib2@3.1.1

spack concretize

spack install

#export ESMFMKFILE=`find ~/spack -name esmf.mk`
#echo export ESMFMKFILE=`find ~/spack -name esmf.mk` >> ~/.bashrc
