#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

if [ "$1" == "2.2.0" ]; then
        VER=v$1
elif [ "$1" == "3.0.0" ]; then
        echo "$1 not yet implemented"
        exit 1
else
        echo "$1 not supported"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
TOP=${UFS_DOMAIN_SELECT_HOME}/build
SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-spack-stack

if [ "$VER" == "2.2.0" ]; then
	echo
	echo "### $0: cloning ufs-srweather-app"
	if [ ! -d $SRC ]; then
		git clone -b release/public-v$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC
	fi
	cd $SRC
	./manage_externals/checkout_externals

	echo
	echo "*** COPYING DEVBUILD.SH ***"
	echo

	cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/ufs-srweather-app-$VER-with-spack-stack/devbuild.sh .

	echo "### $0: activating ufs environment"
        source $TOP/spack-stack-for-2.2.0/share/spack/setup-env.sh
        spack env activate ufs -p

	spack load gcc@11

	echo "### $0: building model"
	./devbuild.sh --platform=foo --compiler=bar

elif [ "$VER" == "3.0.0" ]; then
        echo "$VER not yet implemented"
else
        echo "$VER not supported"
        exit 1
fi
