#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

# Be as specific as needed (e.g., 11, 11.4, 11.4.0)
GCC_VERSION=11
GCC_EXEC=`echo -n "gcc-"; echo $GCC_VERSION | sed 's/\..*//'`

echo "looking for gcc compiler version $GCC_VERSION"

if which=`which $GCC_EXEC`; then
	version=`$GCC_EXEC --version | head -n 1 | awk '{print $4}'`
	echo "$GCC_EXEC found at $which (version $version)"
	read -p "<Enter> to continue the build with gcc-$version"
	prompt_gcc_build=false
else
	echo "$GCC_EXEC not found - you will be asked to build gcc@$GCC_VERSION"
	read -p "<Enter> to continue the build"
	prompt_gcc_build=true
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

TOP=${UFS_DOMAIN_SELECT_HOME}/build/

mkdir -p $TOP

if [ "$VER" == "2.2.0" ]; then

	echo; echo "### $0: cloning spack stack"
	cd $TOP
	git clone -c feature.manyFiles=true https://github.com/spack/spack.git spack-stack-for-$VER
	cd spack-stack-for-$VER
	git checkout 124b9686d153a7e6d6eb9eed7fb318d7fc65272f
	source ./share/spack/setup-env.sh

	if $prompt_gcc_build; then
		read -p "<[y]|n> build gcc@$GCC_VERSION spack package?" val
		if [ "$val" == "y" ] || [ "$val" == "" ]; then
			echo; echo "### $0: creating gcc build environment"
			spack env create gcc_build
			spack env activate gcc_build -p
			spack install --add gcc@$GCC_VERSION
			compilerPath=$(spack location -i gcc@$GCC_VERSION)
			spack env deactivate
			spack compiler add $compilerPath
		fi
	fi

	echo; echo "### $0: creating ufs build environment"
	spack env create ufs
	spack env activate ufs -p

	# Apply cmake flags for the fms package.
	cp $TOP/../stack/patch/spack-stack-for-$VER/package.py `spack location -p fms`

	PACKAGES=("netcdf-c@4.9.2" "netcdf-fortran@4.6.0" "parallelio@2.5.10" \
		"esmf@8.4.2" "bacio@2.4.1" "crtm@2.4.0" "g2@3.4.5" "g2tmpl@1.10.2" \
		"nemsio@2.5.4" "sfcio@1.4.1" "sigio@2.3.2" "sp@2.3.3" "fms@2023.01" "ip@3.3.3" \
		"jasper@2.0.32" "libpng@1.6.37" "jpeg@9.1.0" "mapl@2.35.2 ^esmf@8.4.2" \
		"wgrib2@2.0.8" "w3emc@2.9.2" "gftl-shared@1.5.0" "w3nco@2.4.1" "wrf-io@1.2.0" \
		"openmpi@4.1.2" "cmake@3.31.11")

	for pkg in "${PACKAGES[@]}"; do
		spack add $pkg %gcc@$GCC_VERSION
	done

	spack concretize
	spack install

 	# These are needed to find certain shared libraries
        spack config add 'modules:prefix_inspections:lib64:[LD_LIBRARY_PATH]'
        spack config add 'modules:prefix_inspections:lib:[LD_LIBRARY_PATH]'

elif [ "$VER" == "3.0.0" ]; then
        echo "$VER not yet implemented"
else
        echo "$VER not supported"
        exit 1
fi
