#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

if [ "$1" == "2.2.0" ]; then
        VER=v$1
elif [ "$1" == "3.0.0" ]; then
        echo "$1 not yet implemented"
        exit 1
else
        echo "$1 not supported"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
TOP=${UFS_DOMAIN_SELECT_HOME}/build
SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-spack-lmod-stack

if [ "$VER" == "2.2.0" ]; then

	echo "### $0: cloning ufs-srweather-app"
	git clone -b release/public-v$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC || exit 1
	cd $SRC || exit 1

	echo "### $0: applying needed patches"

	cp $TOP/../stack/patch/ufs-srweather-app-$VER-with-spack-lmod-stack/lmod-setup.sh etc || exit 1
	cp $TOP/../stack/patch/ufs-srweather-app-$VER-with-spack-lmod-stack/srw_common.lua modulefiles || exit 1
	cp $TOP/../stack/patch/ufs-srweather-app-$VER-with-spack-lmod-stack/build_linux_gnu.lua modulefiles || exit 1

	echo "### $0: initializing lmod"
        source $TOP/spack-lmod-stack-for-2.2.0/share/spack/setup-env.sh || exit 1
	source `spack location -i lmod`/lmod/lmod/init/bash || exit 1
	module use $SPACK_ROOT/share/spack/lmod/linux-ubuntu22.04-x86_64/Core || exit 1
	module use $SPACK_ROOT/share/spack/lmod/linux-ubuntu22.04-x86_64/openmpi/5.0.10-fi4liwp/Core || exit 1

	echo "### $0: building model"
	./manage_externals/checkout_externals || exit 1
	./devbuild.sh --platform=linux --compiler=gnu || exit 1

elif [ "$VER" == "3.0.0" ]; then
        echo "$VER not yet implemented"
else
        echo "$VER not supported"
        exit 1
fi
