#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: build-model <2.1.0|2.2.0>"
        exit 1
fi

VER=v$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER

git clone -b release/public-$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC

cd $SRC

./manage_externals/checkout_externals

cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/config.yaml ush
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/devbuild.sh .

./devbuild.sh --platform=foo --compiler=bar
