#!/bin/bash

if [ $# != 1 ]; then
	echo "usage: build-stack <2.1.0|2.2.0>"
	exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

mkdir -p $UFS_DOMAIN_SELECT_HOME/build

git clone https://github.com/NOAA-EMC/hpc-stack.git -b develop ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER

echo "### COPYING PATCH FILES FROM ${UFS_DOMAIN_SELECT_HOME}/stack/patch TO ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER ###"
(cd ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER; git reset fa37037)
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/build_* ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER/libs
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/config_custom-$VER.sh ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER/config/config_custom.sh
cp ${UFS_DOMAIN_SELECT_HOME}/stack/patch/stack_custom-$VER.yaml ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER/stack//stack_custom.yaml

cd ${UFS_DOMAIN_SELECT_HOME}/build/hpc-stack-$VER

source /usr/local/lmod/lmod/init/profile

read -p "<Enter> to configure"
yes YES | ./setup_modules.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-$VER -c ./config/config_custom.sh

read -p "<Enter> to build"
./build_stack.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-$VER -c ./config/config_custom.sh -y stack/stack_custom.yaml -m
