#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: config-anaconda <2.1.0|2.2.0|3.0.0>"
        exit 1
fi

VER=$1

if [ ! "$VER" = "2.2.0" ] && [ ! "$VER" = "3.0.0" ]; then
	echo $VER not yet implemented
	exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

echo ### $0: creating regional_workflow-$VER environment"

${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda env create \
	-f $UFS_DOMAIN_SELECT_HOME/stack/environment-$VER.yml
