#!/bin/bash

if [ $# != 2 ]; then
        echo "usage: $0 <hpc|spack|zee> <2.1.0|2.2.0>"
        exit 1
fi

STACK=$1
VER=$2

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

cd $UFS_DOMAIN_SELECT_HOME/stack

read -p "<[y]|n> install prereqs (sudo required)?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./install-prereqs
fi

read -p "<[y]|n> build $STACK stack for UFS SRW model $VER?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./build-$STACK-stack $VER
fi

read -p "<[y]|n> build UFS SRW model $VER with $STACK stack?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./build-model-with-$STACK-stack $VER
fi

read -p "<[y]|n> install anaconda?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./install-anaconda
fi

read -p "<[y]|n> config anaconda?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	./config-anaconda $VER
fi

read -p "<[y]|n> download input data?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./download-data $VER
fi

read -p "<[y]|n> download earth?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
	time ./download-earth
fi

read -p "<[y]|n> generate and plot a forecast?" val
if [ "$val" == "y" ] || [ "$val" == "" ]; then
        time ../forecast/do-forecast $STACK $VER || exit 1
        time ../forecast/do-post $STACK $VER || exit 1
        time ../forecast/do-plot $STACK $VER || exit 1
        echo
        echo "*** FORECAST COMPLETE ***"
        echo
fi

echo
echo "*"
echo "* You can modify $UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-$VER-with-hpc-stack/ush/config.yaml"
echo "* and execute $UFS_DOMAIN_SELECT_HOME/forecast/do-forecast $STACK $VER to generate another forecast."
echo "*"
echo
