#!/bin/bash

cd ~/tmp/ufs-srweather-app

source ~/ufs_domain_select/build/spack-stack-for-2.2.0/share/spack/setup-env.sh
source `spack location -i lmod`/lmod/lmod/init/bash
module use $SPACK_ROOT/share/spack/lmod/linux-ubuntu22.04-x86_64/Core
module use $SPACK_ROOT/share/spack/lmod/linux-ubuntu22.04-x86_64/openmpi/5.0.10-fi4liwp/Core

./manage_externals/checkout_externals

echo "edit etc/lmod-setup.sh with 'export BASH_ENV=\`spack location -i lmod\`/lmod/lmod/init/bash'"
read -p "<Enter> to continue"

echo "comment out all load(\"hpc-*\") in modulefiles/build_linux_gnu.lua"
read -p "<Enter> to continue"

echo "edit parallelio, gftl-shared, yafyaml and mapl in  modulefiles/srw_common.lua as follows -"  
echo 'load_any("parallelio/2.5.10")'
echo 'load_any("gftl-shared/1.5.0")'
echo 'load_any("yafyaml/0.5.1")'
echo 'load("mapl/2.35.2")'



read -p "<Enter> to continue"

./devbuild.sh --platform=linux --compiler=gnu
