#!/bin/bash

set -e

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

if [ -f ${UFS_DOMAIN_SELECT_HOME}/build/earth/DONE ]; then
	echo "${UFS_DOMAIN_SELECT_HOME}/build/earth already downloaded"
	exit 0
fi

# For plotting
mkdir -p ${UFS_DOMAIN_SELECT_HOME}/build/earth
cd ${UFS_DOMAIN_SELECT_HOME}/build/earth
wget https://naciscdn.org/naturalearth/packages/Natural_Earth_quick_start.zip
unzip -o Natural_Earth_quick_start.zip
cd packages/Natural_Earth_quick_start
ln -sf 50m_raster/NE1_50M_SR_W raster_files
touch ${UFS_DOMAIN_SELECT_HOME}/build/earth/DONE
