#!/bin/bash

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

# For plotting
mkdir ${UFS_DOMAIN_SELECT_HOME}/build/earth
cd ${UFS_DOMAIN_SELECT_HOME}/build/earth
wget https://naciscdn.org/naturalearth/packages/Natural_Earth_quick_start.zip
unzip Natural_Earth_quick_start.zip
cd packages/Natural_Earth_quick_start
ln -s 50m_raster/NE1_50M_SR_W raster_files
