#!/bin/bash

local=1

if [ $# != 1 ]; then
        echo "usage: download-data <2.1.0|2.2.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

mkdir ${UFS_DOMAIN_SELECT_HOME}/build/DATA-$VER
cd ${UFS_DOMAIN_SELECT_HOME}/build/DATA-$VER
rm -f fix_data.tgz
rm -f gst_data.tgz

mkdir -p ${UFS_DOMAIN_SELECT_HOME}/build/DATA-$VER/input_model_data/FV3GFS/grib2
ln -sf ${UFS_DOMAIN_SELECT_HOME}/stack/patch/2026021700 ${UFS_DOMAIN_SELECT_HOME}/build/DATA-$VER/input_model_data/FV3GFS/grib2

if [ $local == 1 ]; then
	wget http://leonard/NOAA/$VER/fix_data.tgz
	tar -vxzf fix_data.tgz
	wget http://leonard/NOAA/$VER/gst_data.tgz
	tar -vxzf gst_data.tgz
else
	wget https://noaa-ufs-srw-pds.s3.amazonaws.com/experiment-user-cases/release-public-v$VER/out-of-the-box/fix_data.tgz
	tar -vxzf fix_data.tgz
	wget https://noaa-ufs-srw-pds.s3.amazonaws.com/experiment-user-cases/release-public-v$VER/out-of-the-box/gst_data.tgz
	tar -vxzf gst_data.tgz
fi
