#!/bin/bash

\rm -rf $HOME/.conda
cd ${UFS_DOMAIN_SELECT_HOME}/build
\rm -rf anaconda3/ Anaconda3-2023.07-2-Linux-x86_64.sh
curl -O https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Linux-x86_64.sh
chmod +x Anaconda3-2023.07-2-Linux-x86_64.sh
./Anaconda3-2023.07-2-Linux-x86_64.sh -b -p ${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/
rm ./Anaconda3-2023.07-2-Linux-x86_64.sh
${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda init
