#!/bin/bash

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

sudo apt update
sudo apt-get install lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
sudo apt-get install tcl tcl8.6-dev libtcl8.6 -y

mkdir -p $UFS_DOMAIN_SELECT_HOME/build

cd $UFS_DOMAIN_SELECT_HOME/build
git clone https://github.com/TACC/Lmod.git
cd Lmod
./configure --with-lua=/usr/bin/lua  --with-luac=/usr/bin/luac
sudo make install
cd ..

source /usr/local/lmod/lmod/init/profile
