#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <hpc|spack>"
        exit 1
fi

STACK=$1

sudo apt update

# For Ubuntu 22 and 24
if cat /etc/issue | awk '{print $2}' | grep -E "^22|^24\."; then
	sudo apt install python-is-python3
fi

# Essential build tools
sudo apt install git curl build-essential gfortran -y

# For viewing forecast plots
sudo apt install ristretto -y

if [ "$STACK" == "hpc" ]; then

	# gcc-11
	if cat /etc/issue | awk '{print $2}' | grep -E "^24\."; then
		sudo apt-get install gcc-11 g++-11 gfortran-11
		sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
			--slave /usr/bin/g++ g++ /usr/bin/g++-11 \
			--slave /usr/bin/gcov gcov /usr/bin/gcov-11 \
			--slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 \
			--slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11 \
			--slave /usr/bin/gfortran gfortran /usr/bin/gfortran-11
	fi

	# Open MPI
	sudo apt install openmpi-bin -y
	sudo apt install openmpi-common libopenmpi-dev -y

	# For cmake
	sudo apt install libssl-dev -y

	# For Lmod
	sudo apt-get install lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
	sudo apt-get install tcl tcl8.6-dev libtcl8.6 -y

	# Lmod
	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	mkdir -p $UFS_DOMAIN_SELECT_HOME/build
	cd $UFS_DOMAIN_SELECT_HOME/build
	git clone https://github.com/TACC/Lmod.git
	cd Lmod
	./configure --with-lua=/usr/bin/lua5.3 --with-luac=/usr/bin/luac5.3 --with-fastTCLInterp=no
	sudo make install

fi
