#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <hpc|spack|zee>"
        exit 1
fi

STACK=$1

sudo apt update
sudo apt install git curl build-essential -y
sudo apt install ristretto -y

# Are these needed?
#sudo ln -sf bash /bin/sh
#sudo apt install python-is-python3 -y

# Compiler
sudo apt install gcc-11 g++-11 gfortran-11 -y
sudo update-alternatives \
	--install /usr/bin/gcc gcc /usr/bin/gcc-11 1000 \
	--slave /usr/bin/g++ g++ /usr/bin/g++-11 \
	--slave /usr/bin/gfortran gfortran /usr/bin/gfortran-11

if [ "$STACK" == "hpc" ]; then
	sudo apt install cmake
	sudo apt install openmpi-bin -y
	sudo apt install openmpi-common libopenmpi-dev -y
	sudo apt install libssl-dev -y
	sudo apt-get install lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
	sudo apt-get install tcl tcl8.6-dev libtcl8.6 -y

	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	mkdir -p $UFS_DOMAIN_SELECT_HOME/build
	cd $UFS_DOMAIN_SELECT_HOME/build
	git clone https://github.com/TACC/Lmod.git
	cd Lmod
	./configure --with-lua=/usr/bin/lua  --with-luac=/usr/bin/luac
	sudo make install
fi
