#!/bin/bash

#
# Packages needed for UFS_domain_select
#

VER="2.2.0"

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"

conda activate regional_workflow-$VER
conda config --add channels conda-forge
conda install -y pygrib cartopy scipy

sudo apt install ristretto -y
