#!/bin/bash

set -e

if conda --version; then
	echo "conda already installed"
	exit 0
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
mkdir -p ${UFS_DOMAIN_SELECT_HOME}/build
\rm -rf $HOME/.conda
cd ${UFS_DOMAIN_SELECT_HOME}/build
\rm -rf anaconda3/ Anaconda3-2023.07-2-Linux-x86_64.sh
curl -O https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Linux-x86_64.sh
chmod +x Anaconda3-2023.07-2-Linux-x86_64.sh
./Anaconda3-2023.07-2-Linux-x86_64.sh -b -p ${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/
rm ./Anaconda3-2023.07-2-Linux-x86_64.sh
${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda init
${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda config --set auto_activate_base false
${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda config --set channel_priority strict
${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda config --set solver libmamba
