#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	echo "This script must be sourced, not executed directly."
	exit 1
fi

export LD_LIBRARY_PATH=""


if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
else
	VER=$1
	UFS_DOMAIN_SELECT_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
	PROFILE=$UFS_DOMAIN_SELECT_HOME/build/lmod/lmod/init/profile
	source $PROFILE
	module use $UFS_DOMAIN_SELECT_HOME/build/opt-for-$VER/modulefiles/stack
	module load hpc hpc-gnu hpc-openmpi
	#module avail
	export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH
	export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/bin:"$PATH
	# Note: LDFLAGS is used during compilation, and LD_LIBRARY_PATH is used during execution
	export LDFLAGS="-L${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/lib -lmpi_cxx"
fi
