#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.1.0|2.2.0>"
else
	VER=$1
	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	source /usr/local/lmod/lmod/init/profile
	module use $UFS_DOMAIN_SELECT_HOME/build/opt-for-$VER/modulefiles/stack
	module load hpc hpc-gnu hpc-openmpi
	module avail
	export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH
	export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11.4/openmpi/4.1.2/bin:"$PATH
	export LD_LIBRARY_PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11.4/openmpi/4.1.2/lib:"$LD_LIBRARY_PATH

fi
