#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

TOP=${UFS_DOMAIN_SELECT_HOME}/build/

if [ "$VER" == "2.2.0" ]; then

	cd $TOP/spack-stack-for-$VER
	source ./share/spack/setup-env.sh

	spack env activate ufs -p

	while [ 1 ]; do
		clear
		spack find -c
		sleep 10
	done

elif [ "$VER" == "3.0.0" ]; then
        echo "$VER not yet implemented"
else
        echo "$VER not supported"
        exit 1
fi
