#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

TOP=$(realpath $(dirname $0))/..

old_hash=0
old_cols=0
old_rows=0

export LMOD_PAGER=none

if [ "$VER" == "2.2.0" ] || [ "$VER" == "3.0.0" ]; then
	while [ ! -f /usr/local/lmod/lmod/init/profile ]; do
		echo "waiting for Lmod to install..."
		sleep 3
	done
	source /usr/local/lmod/lmod/init/profile
	module use $TOP/build/opt-for-$VER/modulefiles/stack
	module load hpc hpc-gnu hpc-openmpi
	while [ 1 ]; do
		new_hash=$(module avail 2>&1 | cksum | awk '{print $1}')
		new_cols=$(tput cols)
		new_rows=$(tput lines)
		if [ $new_hash != $old_hash ] || [ $new_cols != $old_cols ] || [ $new_rows != $old_rows ]; then
			echo "REFRESHING..."; sleep 0.5
			clear
			module avail
			old_hash=$new_hash
			old_rows=$new_rows
			old_cols=$new_cols
		fi
		sleep 1
	done
else
        echo "$VER not supported"
        exit 1
fi
