#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

TOP=$(realpath $(dirname $0))/..

old_hash=0
old_cols=0
old_rows=0

if [ "$VER" == "2.2.0" ]; then
	while [ ! -f $TOP/build/spack-stack-for-$VER/share/spack/setup-env.sh ]; do
		echo "waiting for spack to install..."
		sleep 3
	done
	source $TOP/build/spack-stack-for-$VER/share/spack/setup-env.sh
	while [ 1 ]; do
		new_hash=$(for i in `spack env list`; do spack env activate $i; spack find -c; done | cksum | awk '{print $1}')
		new_cols=$(tput cols)
		new_rows=$(tput lines)
		if [ $new_hash != $old_hash ] || [ $new_cols != $old_cols ] || [ $new_rows != $old_rows ]; then
			echo "REFRESHING..."; sleep 1
			clear
			for i in `spack env list`; do
				spack env activate $i
				spack find -c
				spack env deactivate
				echo
			done
			old_hash=$new_hash
			old_rows=$new_rows
			old_cols=$new_cols
		fi
		sleep 1
	done

elif [ "$VER" == "3.0.0" ]; then
        echo "$VER not yet implemented"
else
        echo "$VER not supported"
        exit 1
fi
