#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <hpc|spack|zee>"
        exit 1
fi

STACK=$1

sudo apt remove git curl build-essential -y
sudo apt remove ristretto -y

if [ "$STACK" == "hpc" ]; then
	sudo apt remove gcc-11 g++-11 gfortran-11 -y
	sudo apt remove cmake
	sudo apt remove openmpi-bin -y
	sudo apt remove openmpi-common libopenmpi-dev -y
	sudo apt remove libssl-dev -y
	sudo apt remove lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
	sudo apt remove tcl tcl8.6-dev libtcl8.6 -y

	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	mkdir -p $UFS_DOMAIN_SELECT_HOME/build
	cd $UFS_DOMAIN_SELECT_HOME/build
	git clone https://github.com/TACC/Lmod.git
	cd Lmod
	./configure --with-lua=/usr/bin/lua  --with-luac=/usr/bin/luac
	sudo make uninstall
	cd ..
	\rm -rf Lmod
fi
