#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <hpc|spack>"
        exit 1
fi

STACK=$1

if [ "$STACK" == "hpc" ]; then

	sudo apt remove openmpi-bin -y
	sudo apt remove openmpi-common libopenmpi-dev -y
	sudo apt remove libssl-dev -y

	sudo apt remove lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
	sudo apt remove tcl tcl8.6-dev libtcl8.6 -y

	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	cd $UFS_DOMAIN_SELECT_HOME/build/Lmod
	sudo make uninstall
	cd ..
	\rm -rf Lmod
	sudo rm /usr/lib/x86_64-linux-gnu/lua/5.3/posix.so
fi

sudo apt remove git curl build-essential -y
sudo apt remove gcc-11 g++-11 gfortran-11 -y
sudo apt remove ristretto -y
