#!/bin/bash

if [ $# != 2 ]; then
        echo "usage: $0 <hpc|spack|zee> <2.2.0|3.0.0>"
        exit 1
fi

if [ ! $1 == "hpc" ] && [ ! $1 == "spack" ] && [ ! $1 == "zee" ]; then
        echo \"$1\" is an invalid stack
        echo "usage: $0 <hpc|spack|zee> <2.2.0|3.0.0>"
        exit 1
fi

if [ "$2" == "2.2.0" ]; then
        STACK=$1
        VER=$2
elif [ "$2" == "3.0.0" ]; then
        echo "$1 not yet implemented"
        exit 1
else
        echo "$2 not supported"
        exit 1
fi

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt
export EXPTDIR=${EXPT_BASEDIR}/test_$STACK

if [ $STACK == "spack" ] || [ $STACK == "zee" ]; then
        source $UFS_DOMAIN_SELECT_HOME/build/$STACK-stack-for-$VER/share/spack/setup-env.sh || exit 1
        if [ $STACK == "spack" ]; then
                echo "### $0: activating ufs spack environment"
                spack env activate ufs -p || exit 1
        else
                echo "### $0: activating zee spack environment"
                spack env activate zee -p || exit 1
        fi
        export LD_LIBRARY_PATH="`spack location -i jasper`/lib:$LD_LIBRARY_PATH"
        export LD_LIBRARY_PATH="`spack location -i netcdf-fortran`/lib:$LD_LIBRARY_PATH"
fi

eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
conda activate regional_workflow-$VER || exit 1

cd $EXPTDIR || exit 1

./run_post.sh || exit 1
