#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: build-model <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

SRC=${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-hpc-stack

cd
if [ ! -d $SRC ]; then
	git clone -b release/public-v$VER https://github.com/ufs-community/ufs-srweather-app.git $SRC
fi
cd $SRC
./manage_externals/checkout_externals || exit 1

cp ${UFS_DOMAIN_SELECT_HOME}/scripts/patch/ufs-srweather-app-$VER-with-hpc-stack/lmod-setup.sh etc

if [ $VER == "3.0.0" ]; then
	cp ${UFS_DOMAIN_SELECT_HOME}/scripts/patch/ufs-srweather-app-$VER-with-hpc-stack/srw_common.lua modulefiles
	cp ${UFS_DOMAIN_SELECT_HOME}/scripts/patch/ufs-srweather-app-$VER-with-hpc-stack/build_linux_gnu.lua modulefiles
	cp ${UFS_DOMAIN_SELECT_HOME}/scripts/patch/ufs-srweather-app-$VER-with-hpc-stack/CMakeLists.txt sorc/UPP/sorc/ncep_post.fd
	cp ${UFS_DOMAIN_SELECT_HOME}/scripts/patch/ufs-srweather-app-$VER-with-hpc-stack/devbuild.sh .
fi

if true ; then

        # Note: devbuild.sh will call build_linux_gnu.lua to load the various modules, set the compiler, etc.
        # If we want to get rid of our bin directory, we can do so by setting the compiler to gcc-11 in
        # build_linux.gnu. This mau be worth doing to simplify things.

        source $UFS_DOMAIN_SELECT_HOME/build/lmod/lmod/init/profile
	module use $UFS_DOMAIN_SELECT_HOME/build/opt-for-$VER/modulefiles/stack
        export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH
        export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/bin:"$PATH
        export LDFLAGS="-L${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/lib -lmpi_cxx"
        export PATH="${UFS_DOMAIN_SELECT_HOME}/bin:"$PATH
	export PATH="/usr/lib/gcc/x86_64-linux-gnu/11:"$PATH
else
	source ../../scripts/load-hpc-stack $VER
fi

export LMOD_PAGER=none
export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/core/cmake/3.20.1/bin:"$PATH

# gcc-11 binaries
export PATH="${UFS_DOMAIN_SELECT_HOME}/scripts/bin:"$PATH
export PATH="/usr/lib/gcc/x86_64-linux-gnu/11:"$PATH

cd $SRC

echo C | ./devbuild.sh --platform=linux --compiler=gnu
