#!/bin/bash

set -e

UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..

CONDA=${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda

if [ $# != 1 ]; then
        echo "usage: config-anaconda <2.2.0|3.0.0>"
        exit 1
fi

VER=$1

if [ ! "$VER" = "2.2.0" ] && [ ! "$VER" = "3.0.0" ]; then
	echo $VER not yet implemented
	exit 1
fi

echo "### $0: creating regional_workflow-$VER environment"
if $CONDA env list | grep -E "regional_workflow-$VER" > /dev/null; then
	echo regional_workflow-$VER environment already created
else
	$CONDA env create -f $UFS_DOMAIN_SELECT_HOME/scripts/environment-$VER.yml
fi

#echo "### $0: creating ufs_domain_select environment"
#if $CONDA env list | grep -E "ufs_domain_select$" > /dev/null; then
#	echo ufs_domain_select environment already created
#else
#	$CONDA env create -f $UFS_DOMAIN_SELECT_HOME/scripts/ufs_domain_select.yml
#fi
