#!/bin/bash

if [ $# != 1 ]; then
        echo "usage: $0 <2.2.0|3.0.0>"
fi

VER=$1

UFS_DOMAIN_SELECT_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

cd $UFS_DOMAIN_SELECT_HOME/build/hpc-stack-for-$VER/log

source $UFS_DOMAIN_SELECT_HOME/scripts/load-hpc-stack $VER

for i in `ls *.log`; do 
	if cat $i | grep Error | grep -v Ignored | grep -v ignored | \
		grep Error > /dev/null; then
		pkg=`echo $i | sed 's/\./ /' | awk '{print $1}'`
		if ! module avail 2>&1 | grep " $pkg"; then
			echo $pkg DID NOT INSTALL
		fi
	fi;
done
