#!/bin/bash

set -e

if [ $# != 1 ]; then
        echo "usage: $0 <hpc|spack>"
        exit 1
fi

STACK=$1

sudo apt update

if cat /etc/issue | awk '{print $2}' | grep -E "^18"; then
	sudo apt install python
elif cat /etc/issue | awk '{print $2}' | grep -E "^20|^22|^24"; then
	sudo apt install python-is-python3
fi

# Essential build tools
sudo apt install git curl build-essential -y

# For viewing forecast plots
sudo apt install ristretto -y
if cat /etc/issue | awk '{print $2}' | grep -E "^18"; then
	sudo apt-get install libcanberra-gtk-module libcanberra-gtk0
fi

if [ "$STACK" == "hpc" ]; then

	# compiler
	if cat /etc/issue | awk '{print $2}' | grep -E "^18|^20|^24"; then
		if cat /etc/issue | awk '{print $2}' | grep -E "^18"; then
			sudo apt-get install m4
		fi
		if cat /etc/issue | awk '{print $2}' | grep -E "^18|^20"; then
		        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        		sudo apt update
			sudo apt-get install libexpat1-dev
		fi
		sudo apt-get install gcc-11 g++-11
	fi
	sudo apt install gfortran-11

	# For cmake
	sudo apt install libssl-dev -y

	# For Lmod
	sudo apt-get install lua5.3 liblua5.3-0 liblua5.3-dev lua-filesystem-dev lua-posix-dev -y
	sudo apt-get install tcl tcl8.6-dev libtcl8.6 -y

	# For Lua
	sudo apt install luarocks
	sudo luarocks install luaposix

	# Lmod
	export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
	mkdir -p $UFS_DOMAIN_SELECT_HOME/build
	cd $UFS_DOMAIN_SELECT_HOME/build
	if [ ! -d Lmod ]; then
		git clone https://github.com/TACC/Lmod.git
		cd Lmod
		./configure --with-lua=/usr/bin/lua5.3 --with-luac=/usr/bin/luac5.3 \
			--with-fastTCLInterp=no \
			--prefix=$UFS_DOMAIN_SELECT_HOME/build
		make install
	else
		echo "Lmod already installed."
	fi

fi
